export const enum QueryModule {
   Healthcheck = "HealthcheckQueries",
   UserAuth = "UserAuthQueries",
   Waitlist = "WaitlistQueries",
   User = "UserQueries",
   PushNotifications = "PushNotificationsQueries",
   Media = "MediaQueries",
   Provider = "ProviderQueries",
   Neighborhood = "NeighborhoodQueries",
   Program = "ProgramQueries",
   Tag = "TagQueries",
   Notification = "NotificationQueries",
   ProgramReview = "ProgramReviewQueries",
   ProviderReview = "ProviderReviewQueries",
   ReviewReport = "ReviewReportQueries",
   UserBlock = "UserBlockQueries",
   Feedback = "FeedbackQueries",
   Contact = "ContactQueries",
   Home = "HomeQueries",
   Favorite = "FavoriteQueries",
   Location = "LocationQueries",
}