import type { BaseTheme } from "@shopify/restyle";

// write all your custom non-theme config here
export const baseRestyleConfig: BaseTheme = {
  colors: {
    transparent: "transparent",
  },
  borderRadii: {},
  spacing: {},
  breakpoints: {
    smallPhone: 0,
    phone: 412,
    tablet: 768,
    tabletLandscape: 1024,
  },
  textVariants: {
    "display-1-default": {
      fontSize: 56,
      fontFamily: "Syne-Medium",
      lineHeight: 68,
    },
    "display-1-prominent-1": {
      fontSize: 56,
      fontFamily: "Syne-SemiBold",
      lineHeight: 68,
    },
    "display-2-default": {
      fontSize: 44,
      fontFamily: "Syne-Medium",
      lineHeight: 56,
    },
    "display-2-prominent-1": {
      fontSize: 44,
      fontFamily: "Syne-SemiBold",
      lineHeight: 56,
    },
    "display-3-default": {
      fontSize: 36,
      fontFamily: "Syne-Medium",
      lineHeight: 44,
    },
    "display-3-prominent-1": {
      fontSize: 36,
      fontFamily: "Syne-SemiBold",
      lineHeight: 44,
    },
    "display-4-default": {
      fontSize: 32,
      fontFamily: "Syne-Medium",
      lineHeight: 40,
    },
    "display-4-prominent-1": {
      fontSize: 32,
      fontFamily: "Syne-SemiBold",
      lineHeight: 40,
    },
    "title-1-default": {
      fontSize: 28,
      fontFamily: "Inter-Regular",
      lineHeight: 36,
    },
    "title-1-prominent-1": {
      fontSize: 28,
      fontFamily: "Inter-Medium",
      lineHeight: 36,
    },
    "title-2-default": {
      fontSize: 24,
      fontFamily: "Inter-Regular",
      lineHeight: 32,
    },
    "title-2-prominent-1": {
      fontSize: 24,
      fontFamily: "Inter-Medium",
      lineHeight: 32,
    },
    "title-3-default": {
      fontSize: 18,
      fontFamily: "Inter-Regular",
      lineHeight: 26,
    },
    "title-3-prominent-1": {
      fontSize: 18,
      fontFamily: "Inter-Medium",
      lineHeight: 26,
    },
    "title-4-default": {
      fontSize: 16,
      fontFamily: "Inter-Regular",
      lineHeight: 24,
    },
    "title-4-prominent-1": {
      fontSize: 16,
      fontFamily: "Inter-Medium",
      lineHeight: 24,
    },
    "body-1-default": {
      fontSize: 18,
      fontFamily: "Inter-Regular",
      lineHeight: 28,
    },
    "body-1-default-italic": {
      fontSize: 18,
      fontFamily: "Inter-Regular-Italic",
      lineHeight: 28,
    },
    "body-1-prominent-1": {
      fontSize: 18,
      fontFamily: "Inter-Medium",
      lineHeight: 28,
    },
    "body-1-prominent-1-italic": {
      fontSize: 18,
      fontFamily: "Inter-Medium-Italic",
      lineHeight: 28,
    },
    "body-1-prominent-2": {
      fontSize: 18,
      fontFamily: "Inter-SemiBold",
      lineHeight: 28,
    },
    "body-1-prominent-2-italic": {
      fontSize: 18,
      fontFamily: "Inter-SemiBold-Italic",
      lineHeight: 28,
      fontStyle: "italic",
    },
    "body-2-default": {
      fontSize: 16,
      fontFamily: "Inter-Regular",
      lineHeight: 28,
    },
    "body-2-default-italic": {
      fontSize: 16,
      fontFamily: "Inter-Regular-Italic",
      lineHeight: 28,
    },
    "body-2-prominent-1": {
      fontSize: 16,
      fontFamily: "Inter-Medium",
      lineHeight: 28,
    },
    "body-2-prominent-1-italic": {
      fontSize: 16,
      fontFamily: "Inter-Medium-Italic",
      lineHeight: 28,
    },
    "body-2-prominent-2": {
      fontSize: 16,
      fontFamily: "Inter-SemiBold",
      lineHeight: 28,
    },
    "body-2-prominent-2-italic": {
      fontSize: 16,
      fontFamily: "Inter-SemiBold-Italic",
      lineHeight: 28,
    },
    "body-3-default": {
      fontSize: 15,
      fontFamily: "Inter-Regular",
      lineHeight: 26,
    },
    "body-3-default-italic": {
      fontSize: 15,
      fontFamily: "Inter-Regular-Italic",
      lineHeight: 26,
    },
    "body-3-prominent-1": {
      fontSize: 15,
      fontFamily: "Inter-Medium",
      lineHeight: 26,
    },
    "body-3-prominent-1-italic": {
      fontSize: 15,
      fontFamily: "Inter-Medium-Italic",
      lineHeight: 26,
    },
    "body-3-prominent-2": {
      fontSize: 15,
      fontFamily: "Inter-SemiBold",
      lineHeight: 26,
    },
    "body-3-prominent-2-italic": {
      fontSize: 15,
      fontFamily: "Inter-SemiBold-Italic",
      lineHeight: 26,
    },
    "body-4-default": {
      fontSize: 14,
      fontFamily: "Inter-Regular",
      lineHeight: 24,
    },
    "body-4-default-italic": {
      fontSize: 14,
      fontFamily: "Inter-Regular-Italic",
      lineHeight: 24,
    },
    "body-4-prominent-1": {
      fontSize: 14,
      fontFamily: "Inter-Medium",
      lineHeight: 24,
    },
    "body-4-prominent-1-italic": {
      fontSize: 14,
      fontFamily: "Inter-Medium-Italic",
      lineHeight: 24,
    },
    "body-4-prominent-2": {
      fontSize: 14,
      fontFamily: "Inter-SemiBold",
      lineHeight: 24,
    },
    "body-4-prominent-2-italic": {
      fontSize: 14,
      fontFamily: "Inter-SemiBold-Italic",
      lineHeight: 24,
    },
    "label-1-default": {
      fontSize: 16,
      fontFamily: "Inter-Medium",
      lineHeight: 24,
    },
    "label-1-prominent-1": {
      fontSize: 16,
      fontFamily: "Inter-SemiBold",
      lineHeight: 24,
    },
    "label-2-default": {
      fontSize: 14,
      fontFamily: "Inter-Medium",
      lineHeight: 24,
    },
    "label-2-prominent-1": {
      fontSize: 14,
      fontFamily: "Inter-SemiBold",
      lineHeight: 24,
    },
    "label-3-default": {
      fontSize: 12,
      fontFamily: "Inter-Medium",
      lineHeight: 16,
    },
    "label-3-prominent-1": {
      fontSize: 12,
      fontFamily: "Inter-SemiBold",
      lineHeight: 16,
    },
    defaults: {
      fontSize: 14,
      fontFamily: "Inter-Regular",
      lineHeight: 24,
    },
  },
  buttonVariants: {
    primary: {
      color: "interactive-primary-on",
      colorPressed: "interactive-primary-on",
      colorDisabled: "interactive-primary-on",
      backgroundColor: "interactive-primary-idle",
      backgroundColorPressed: "interactive-primary-pressed",
      backgroundColorDisabled: "interactive-primary-disabled",
      borderColor: "transparent",
      borderColorPressed: "transparent",
      borderColorDisabled: "transparent",
    },
    secondary: {
      color: "interactive-primary-on",
      colorPressed: "interactive-primary-on",
      colorDisabled: "interactive-primary-on",
      backgroundColor: "interactive-secondary-idle",
      backgroundColorPressed: "interactive-secondary-pressed",
      backgroundColorDisabled: "interactive-secondary-disabled",
      borderColor: "transparent",
      borderColorPressed: "transparent",
      borderColorDisabled: "transparent",
    },
    outlined: {
      color: "interactive-outlined-idle",
      colorPressed: "interactive-outlined-pressed",
      colorDisabled: "interactive-outlined-disabled",
      backgroundColor: "transparent",
      backgroundColorPressed: "transparent",
      backgroundColorDisabled: "transparent",
      borderColor: "interactive-outlined-idle",
      borderColorPressed: "interactive-outlined-pressed",
      borderColorDisabled: "interactive-outlined-disabled",
    },
  },
  buttonWidths: {
    s: 112,
    m: 156,
    l: 192,
    fit: "100%",
  },
  buttonSizes: {
    small: "height-height-s",
    default: "height-height-m",
    large: "height-height-l",
  },
  iconButtonVariants: {
    primary: {
      color: "interactive-primary-on",
      colorPressed: "interactive-primary-on",
      colorDisabled: "interactive-primary-on",
      backgroundColor: "interactive-primary-idle",
      backgroundColorPressed: "interactive-primary-pressed",
      backgroundColorDisabled: "interactive-primary-disabled",
      borderColor: "transparent",
      borderColorPressed: "transparent",
      borderColorDisabled: "transparent",
    },
    secondary: {
      color: "interactive-primary-on",
      colorPressed: "interactive-primary-on",
      colorDisabled: "interactive-primary-on",
      backgroundColor: "interactive-secondary-idle",
      backgroundColorPressed: "interactive-secondary-pressed",
      backgroundColorDisabled: "interactive-secondary-disabled",
      borderColor: "transparent",
      borderColorPressed: "transparent",
      borderColorDisabled: "transparent",
    },
    outlined: {
      color: "interactive-outlined-idle",
      colorPressed: "interactive-outlined-pressed",
      colorDisabled: "interactive-outlined-disabled",
      backgroundColor: "transparent",
      backgroundColorPressed: "transparent",
      backgroundColorDisabled: "transparent",
      borderColor: "interactive-outlined-idle",
      borderColorPressed: "interactive-outlined-pressed",
      borderColorDisabled: "interactive-outlined-disabled",
    },
    transparent: {
      color: "interactive-icon-idle",
      colorPressed: "interactive-icon-pressed",
      colorDisabled: "interactive-icon-disabled",
      backgroundColor: "transparent",
      backgroundColorPressed: "transparent",
      backgroundColorDisabled: "transparent",
      borderColor: "transparent",
      borderColorPressed: "transparent",
      borderColorDisabled: "transparent",
      borderColorDisabledToggled: "transparent",
    },
  },
  iconButtonSizes: {
    s: "height-height-s",
    m: "height-height-m",
    l: "height-height-l",
  },
  inputVariants: {
    outlined: {
      backgroundColor: "elevation-background",
      backgroundColorActive: "elevation-background",
      backgroundColorError: "elevation-background",
      backgroundColorDisabled: "elevation-background",
      borderColor: "elevation-outline-2",
      borderColorActive: "interactive-primary-idle",
      borderColorError: "informational-error-outline",
      borderColorDisabled: "elevation-outline-2",
      color: "text-default-primary",
      colorActive: "text-default-primary",
      colorError: "text-default-primary",
      colorDisabled: "interactive-text-disabled",
      labelColor: "text-default-primary",
      labelColorActive: "text-default-primary",
      labelColorError: "text-default-primary",
      labelColorDisabled: "interactive-text-disabled",
    },
    filled: {
      backgroundColor: "elevation-surface-2",
      backgroundColorActive: "elevation-background",
      backgroundColorError: "elevation-surface-2",
      backgroundColorDisabled: "elevation-surface-2",
      borderColor: "transparent",
      borderColorActive: "interactive-primary-idle",
      borderColorError: "informational-error-outline",
      borderColorDisabled: "transparent",
      color: "text-default-primary",
      colorActive: "text-default-primary",
      colorError: "text-default-primary",
      colorDisabled: "interactive-text-disabled",
      labelColor: "text-default-primary",
      labelColorActive: "text-default-primary",
      labelColorError: "text-default-primary",
      labelColorDisabled: "interactive-text-disabled",
    },
  },
  pillVariants: {
    primary: {
      color: "interactive-tertiary-on",
      colorPressed: "interactive-tertiary-on",
      colorDisabled: "interactive-tertiary-on-disabled",
      backgroundColor: "interactive-tertiary-idle",
      backgroundColorPressed: "interactive-tertiary-pressed",
      backgroundColorDisabled: "interactive-tertiary-idle",
      borderColor: "transparent",
      borderColorPressed: "transparent",
      borderColorDisabled: "transparent",
      borderColorDisabledToggled: "transparent",
    },
    toggle: {
      color: "interactive-tertiary-on",
      colorPressed: "interactive-tertiary-on",
      colorDisabled: "interactive-tertiary-on-disabled",
      backgroundColor: "interactive-tertiary-idle",
      backgroundColorPressed: "interactive-tertiary-idle",
      backgroundColorDisabled: "interactive-tertiary-idle",
      borderColor: "transparent",
      borderColorPressed: "interactive-tertiary-toggled",
      borderColorDisabled: "transparent",
      borderColorDisabledToggled: "interactive-tertiary-on-disabled",
    },
    filled: {
      color: "pill-default-text",
      colorPressed: "pill-default-text",
      colorDisabled: "pill-default-text",
      backgroundColor: "transparent",
      backgroundColorPressed: "transparent",
      backgroundColorDisabled: "transparent",
      borderColor: "pill-default-border",
      borderColorPressed: "pill-filled-border",
      borderColorDisabled: "pill-default-border",
      borderColorDisabledToggled: "pill-default-border",
      backgroundColorToggled: "pill-filled-bg",
      borderColorToggled: "pill-filled-border",
    },
    outlined: {
      color: "pill-default-text",
      colorPressed: "pill-default-text",
      colorDisabled: "pill-default-text",
      backgroundColor: "transparent",
      backgroundColorPressed: "transparent",
      backgroundColorDisabled: "transparent",
      borderColor: "pill-default-border",
      borderColorPressed: "pill-outlined-border",
      borderColorDisabled: "pill-default-border",
      borderColorDisabledToggled: "pill-default-border",
      backgroundColorToggled: "pill-outlined-bg",
      borderColorToggled: "pill-outlined-border",
    },
    active: {
      color: "interactive-primary-on",
      colorPressed: "interactive-primary-on",
      colorDisabled: "interactive-text-disabled",
      backgroundColor: "pill-outlined-border",
      backgroundColorPressed: "pill-outlined-border",
      backgroundColorDisabled: "interactive-tertiary-idle",
      borderColor: "pill-outlined-border",
      borderColorPressed: "pill-outlined-border",
      borderColorDisabled: "pill-default-border",
      borderColorDisabledToggled: "pill-default-border",
    },
  },
  textButtonVariants: {
    dual: {
      color: "interactive-text-on-bg",
      colorPressed: "interactive-text-pressed",
      colorDisabled: "interactive-text-disabled",
      backgroundColor: "transparent",
      backgroundColorPressed: "transparent",
      backgroundColorDisabled: "transparent",
      iconColor: "interactive-text-on-bg-2",
      iconColorPressed: "interactive-text-pressed",
      iconColorDisabled: "interactive-text-disabled",
    },
    secondary: {
      color: "interactive-text-on-bg",
      colorPressed: "interactive-text-pressed",
      colorDisabled: "interactive-text-disabled",
      backgroundColor: "transparent",
      backgroundColorPressed: "transparent",
      backgroundColorDisabled: "transparent",
      iconColor: "interactive-text-on-bg",
      iconColorPressed: "interactive-text-pressed",
      iconColorDisabled: "interactive-text-disabled",
    },
    primary: {
      color: "interactive-text-on-bg-2",
      colorPressed: "interactive-text-pressed",
      colorDisabled: "interactive-text-disabled",
      backgroundColor: "transparent",
      backgroundColorPressed: "transparent",
      backgroundColorDisabled: "transparent",
      iconColor: "interactive-text-on-bg-2",
      iconColorPressed: "interactive-text-pressed",
      iconColorDisabled: "interactive-text-disabled",
    },
    toast: {
      backgroundColor: "transparent",
      backgroundColorPressed: "transparent",
      backgroundColorDisabled: "transparent",
      color: "interactive-text-on-inverted",
      colorPressed: "interactive-text-pressed",
      colorDisabled: "interactive-text-disabled",
      iconColor: "interactive-text-on-inverted",
      iconColorPressed: "interactive-text-pressed",
      iconColorDisabled: "interactive-text-disabled",
    },
  },
  toastVariants: {
    neutral: {
      backgroundColor: "interactive-secondary-idle",
    },
    success: {
      backgroundColor: "informational-success",
    },
    warning: {
      backgroundColor: "informational-warning",
    },
    error: {
      backgroundColor: "informational-error",
    },
  },
  listItems: {
    single: {
      backgroundColor: "transparent",
      backgroundColorSelected: "interactive-primary-idle",
      backgroundColorPressed: "transparent",
      labelColor: "interactive-text-on-bg",
      labelColorSelected: "interactive-text-on-inverted",
      labelColorPressed: "interactive-text-pressed",
      sublabelColor: "text-default-tertiary",
      sublabelColorSelected: "text-inverted-tertiary",
      borderColor: "elevation-outline-1",
      borderRadius: "none",
    },
    multiple: {
      backgroundColor: "transparent",
      backgroundColorSelected: "transparent",
      backgroundColorPressed: "transparent",
      labelColor: "interactive-text-on-bg",
      labelColorSelected: "interactive-text-on-bg",
      labelColorPressed: "interactive-text-pressed",
      sublabelColor: "text-default-tertiary",
      sublabelColorSelected: "text-default-tertiary",
      borderColor: "elevation-outline-1",
      borderRadius: "none",
    },
    action: {
      backgroundColor: "elevation-background",
      backgroundColorSelected: "elevation-background",
      backgroundColorPressed: "elevation-background",
      labelColor: "interactive-text-on-bg",
      labelColorSelected: "interactive-text-on-inverted",
      labelColorPressed: "interactive-text-pressed",
      sublabelColor: "text-default-tertiary",
      sublabelColorSelected: "text-inverted-tertiary",
      borderColor: "transparent",
      borderRadius: "4xl",
    },
  },
  shadows: {
    "shadow-1": {
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.2,
      shadowRadius: 1,
      elevation: 3,
    },
    "shadow-2": {
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.2,
      shadowRadius: 2.22,
      elevation: 5,
    },
    "shadow-3": {
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.15,
      shadowRadius: 2.62,
      elevation: 8,
    },
    "shadow-4": {
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 12,
      },
      shadowOpacity: 0.15,
      shadowRadius: 16,
      elevation: 16,
    },
  },
  blurs: {
    "bg-blur-0": 0,
    "bg-blur-1": 10,
    "bg-blur-2": 20,
    "bg-blur-3": 30,
    "bg-blur-4": 50,
    "bg-blur-5": 60,
    "bg-blur-6": 70,
    "bg-blur-7": 80,
  },
};

export const restyleConfigTemplate = (jsonConfig: string) => {
  return `
  import { createTheme } from "@shopify/restyle";

  const theme = createTheme(${jsonConfig});
  
  export type Theme = typeof theme;
  export type ThemeColor = keyof Theme["colors"];
  
  export default theme;  
`;
};
